# Generated by Django 3.1.2 on 2021-01-29 22:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('codigo', models.IntegerField(primary_key=True, serialize=False, verbose_name='Codigo')),
                ('descricao', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('codigo', models.IntegerField(primary_key=True, serialize=False, verbose_name='Codigo')),
                ('descricao', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Escola',
            fields=[
                ('codigo', models.IntegerField(primary_key=True, serialize=False, verbose_name='Codigo')),
                ('descricao', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('codigo', models.IntegerField(primary_key=True, serialize=False, verbose_name='Codigo')),
                ('descricao', models.CharField(max_length=100)),
                ('escola', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turmas', to='dashboard.escola')),
            ],
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('codigo', models.IntegerField(primary_key=True, serialize=False, verbose_name='Codigo')),
                ('descricao', models.CharField(max_length=100)),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='professores', to='dashboard.disciplina')),
            ],
        ),
        migrations.CreateModel(
            name='Habilidade',
            fields=[
                ('codigo', models.IntegerField(primary_key=True, serialize=False, verbose_name='Codigo')),
                ('descricao', models.CharField(max_length=100)),
                ('alunos', models.ManyToManyField(blank=True, related_name='habilidades', to='dashboard.Aluno')),
            ],
        ),
        migrations.AddField(
            model_name='disciplina',
            name='turma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disciplinas', to='dashboard.turma'),
        ),
        migrations.AddField(
            model_name='aluno',
            name='turma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alunos', to='dashboard.turma'),
        ),
    ]
