# Generated by Django 3.1.2 on 2021-02-01 20:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('codigo', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Codigo')),
                ('nome', models.CharField(default='', max_length=50)),
                ('descricao', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'ordering': ['-codigo'],
            },
        ),
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('nome', models.CharField(default='', max_length=50)),
                ('codigo', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Codigo')),
                ('descricao', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'ordering': ['-codigo'],
            },
        ),
        migrations.CreateModel(
            name='Escola',
            fields=[
                ('codigo', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Codigo')),
                ('nome', models.CharField(default='', max_length=50)),
                ('descricao', models.CharField(blank=True, max_length=100)),
                ('user', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='escolas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-codigo'],
            },
        ),
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('codigo', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Codigo')),
                ('descricao', models.CharField(blank=True, max_length=100)),
                ('escola', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turmas', to='dashboard.escola')),
                ('user', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='turmas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-codigo'],
            },
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('nome', models.CharField(default='', max_length=50)),
                ('codigo', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Codigo')),
                ('descricao', models.CharField(blank=True, max_length=100)),
                ('disciplina', models.ManyToManyField(related_name='professores', to='dashboard.Disciplina')),
                ('user', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='professores', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-codigo'],
            },
        ),
        migrations.CreateModel(
            name='Habilidade',
            fields=[
                ('codigo', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Codigo')),
                ('nome', models.CharField(default='', max_length=50)),
                ('descricao', models.CharField(blank=True, max_length=100)),
                ('alunos', models.ManyToManyField(blank=True, related_name='habilidades', to='dashboard.Aluno')),
                ('user', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='habilidades', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-codigo'],
            },
        ),
        migrations.AddField(
            model_name='disciplina',
            name='turma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disciplinas', to='dashboard.turma'),
        ),
        migrations.AddField(
            model_name='disciplina',
            name='user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='disciplinas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='aluno',
            name='turma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alunos', to='dashboard.turma'),
        ),
        migrations.AddField(
            model_name='aluno',
            name='user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='alunos', to=settings.AUTH_USER_MODEL),
        ),
    ]
