# Generated by Django 3.1.2 on 2021-02-02 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='disciplina',
            name='habilidades_ofertadas',
            field=models.ManyToManyField(blank=True, related_name='subjects_o', to='dashboard.Habilidade'),
        ),
        migrations.AddField(
            model_name='disciplina',
            name='habilidades_requeridas',
            field=models.ManyToManyField(blank=True, related_name='subjects_r', to='dashboard.Habilidade'),
        ),
    ]
