# Generated by Django 3.1.2 on 2021-01-31 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_habilidade_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='professor',
            name='disciplina',
        ),
        migrations.AddField(
            model_name='professor',
            name='disciplina',
            field=models.ManyToManyField(related_name='professores', to='dashboard.Disciplina'),
        ),
    ]
