# Generated by Django 3.1.2 on 2021-01-31 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_auto_20210131_2240'),
    ]

    operations = [
        migrations.AddField(
            model_name='escola',
            name='nome',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='escola',
            name='codigo',
            field=models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Codigo'),
        ),
    ]
