# Generated by Django 3.1.2 on 2021-01-31 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_auto_20210131_2337'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='nome',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='disciplina',
            name='nome',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='habilidade',
            name='nome',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='professor',
            name='nome',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='turma',
            name='codigo',
            field=models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Codigo'),
        ),
    ]
