# Generated by Django 3.1.2 on 2021-02-01 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_auto_20210131_2349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='codigo',
            field=models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Codigo'),
        ),
        migrations.AlterField(
            model_name='disciplina',
            name='codigo',
            field=models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Codigo'),
        ),
        migrations.AlterField(
            model_name='habilidade',
            name='codigo',
            field=models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Codigo'),
        ),
        migrations.AlterField(
            model_name='professor',
            name='codigo',
            field=models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Codigo'),
        ),
    ]
