# Generated by Django 3.1.2 on 2021-02-01 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_auto_20210201_0244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disciplina',
            name='descricao',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='habilidade',
            name='descricao',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='professor',
            name='descricao',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
