# Generated by Django 3.1.2 on 2021-02-01 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_auto_20210201_1415'),
    ]

    operations = [
        migrations.AddField(
            model_name='habilidade',
            name='disciplinas_c_h_obg',
            field=models.ManyToManyField(blank=True, related_name='habilidades', to='dashboard.Disciplina'),
        ),
    ]
