# Generated by Django 3.1.2 on 2021-02-01 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0015_auto_20210201_1446'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='habilidade',
            name='disciplinas_c_h_obg',
        ),
        migrations.RemoveField(
            model_name='habilidade',
            name='disciplinas_c_h_ofe',
        ),
    ]
